### ISSUE TITLE
Segmentation fault on opening the context menu multiple times on a package

### ISSUE THREAD

**Issue by Socialdarwinist** [teeuniverse/teeuniverse#169]
Gdb spits out the following:
```
Thread 1 "teeuniverse_edi" received signal SIGSEGV, Segmentation fault.
0x00000000006ec188 in std::vector<gui::CPopup*, std::allocator<gui::CPopup*> >::push_back (this=0x58, __x=@0x7fffffffe380: 0x780fe10)
    at /usr/include/c++/6.3.1/bits/stl_vector.h:916
916		if (this->_M_impl._M_finish != this->_M_impl._M_end_of_storage)
(gdb) bt
#0  0x00000000006ec188 in std::vector<gui::CPopup*, std::allocator<gui::CPopup*> >::push_back (this=0x58, __x=@0x7fffffffe380: 0x780fe10)
    at /usr/include/c++/6.3.1/bits/stl_vector.h:916
#1  0x00000000006ebd57 in CGui::DisplayPopup (this=0x0, pPopup=0x780fe10)
    at ~/teeuniverse/src/client/components/gui.cpp:382
#2  0x000000000063c6a1 in CPackageItem::OnButtonClick (this=0x77d8110, 
    Button=412) at ~/teeuniverse/src/editor/gui/assetslist.cpp:186
#3  0x00000000006c84de in gui::CExpand::OnButtonClick (this=0x282d540, 
    Button=412) at ~/teeuniverse/src/client/gui/expand.cpp:213
#4  0x00000000006cc988 in gui::CAbstractListLayout::OnButtonClick (
    this=0x282d400, Button=412)
    at ~/teeuniverse/src/client/gui/listlayout.cpp:115
#5  0x00000000006ce688 in gui::CVScrollLayout::OnButtonClick (this=0x282d400, 
    Button=412) at ~/teeuniverse/src/client/gui/listlayout.cpp:592
#6  0x00000000006cf6c4 in gui::CAbstractPanelLayout::OnButtonClick (
    this=0x29bc180, Button=412)
    at ~/teeuniverse/src/client/gui/panellayout.cpp:106
#7  0x00000000006cf6c4 in gui::CAbstractPanelLayout::OnButtonClick (
    this=0x29bbd30, Button=412)
    at ~/teeuniverse/src/client/gui/panellayout.cpp:106
#8  0x00000000006cc988 in gui::CAbstractListLayout::OnButtonClick (
    this=0x281f960, Button=412)
    at ~/src/client/gui/listlayout.cpp:115
```

**Comment by Socialdarwinist** [comment]
The weight of the bug is even higher, as I have noticed that the editor always crashes if one just starts the editor, opens a package and right thereafter right-clicks on it.
