### ISSUE TITLE
Interface freeze on clicking materials

### ISSUE THREAD

**Issue by Socialdarwinist** [teeuniverse/teeuniverse#188]
I have had the TeeUniverse editor’s interface freezing while clicking materials in infc_chashitsu, necessitating forceful termination of the program. I have had success in reproducing it once in gdb.

```
Thread 1 "teeuniverse_edi" received signal SIGTERM, Terminated.
0x00000000006fb9bb in CGraphics::QuadsDraw (this=0x7ffff7e67010, 
    pArray=0x7fffffffe010, Num=1)
    at ~/teeuniverse/src/client/components/graphics.cpp:623
623			pArray[i].m_X -= pArray[i].m_Width/2;
(gdb) bt
#0  0x00000000006fb9bb in CGraphics::QuadsDraw (this=0x7ffff7e67010, 
    pArray=0x7fffffffe010, Num=1)
    at ~/teeuniverse/src/client/components/graphics.cpp:623
#1  0x00000000006f50ec in CAssetsRenderer::DrawGuiRect (
    this=<error reading variable: Cannot access memory at address 0x7fffffffdf98>, 
    pRect=<error reading variable: Cannot access memory at address 0x7fffffffdf90>, 
    StylePath=<error reading variable: Cannot access memory at address 0x7fffffffdf80>) at ~/teeuniverse/src/client/components/assetsrenderer.cpp:415
Backtrace stopped: Cannot access memory at address 0x7fffffffe1d8
```
I want to address here also that in general displaying materials is suspiciously slow.

**Comment by necropotame** [comment]
I will track that, thanks
Concerning the material rendering, you mean in map, during edition of map, or when you click on the material bin the asset list?

**Comment by Socialdarwinist** [comment]
I only clicked in the asset list. I do not know though exactly which circumstances trigger the bug. It might also have to do something with changing windows in the desktop environment, because both times I noticed it frozen when changing back to the TeeUniverse editor.

**Comment by EmeraldyDE** [comment]
That problem isn't existing on  windows 🗡

**Comment by necropotame** [comment]
Your trace show that it crashes during the rendering of some gui part. I don't think that it came from this part of the code. It's probably a more low level bug in the rendering pipe-line, maybe like you said, after some desktop event. I can't reproduce it for now :(
